<?php
/**
 * @author Alexander Akimov
 * @license MIT
 */
?>
<!doctype html>
<html lang="en">
<head>
    <title><?php echo __('Magento 2 Best in Class Experience') ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo __('Magento 2 Best in Class Experience') ?>">
    <meta name="author" content="Alexander Akimov">

    <!-- Fancy minified bootstrap for better experience -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <style>
        body {
            padding-top: 15px;
        };
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="jumbotron">
        <h1><?php echo __('So, you are here...') ?></h1>
        <p><?php echo __("Don't worry everything will be alright. You are not alone. Many people have already made the same mistake as you. Best in class experience is almost there.") ?></p>
        <h1><?php echo __('Your next steps...') ?></h1>
        <p><?php echo __('Just click a link and start a new life full of real best in class experience:') ?></p>
        <ul>
            <li><a href="https://www.bigcommerce.com/">https://www.bigcommerce.com/</a></li>
            <li><a href="https://www.shopify.com/">https://www.shopify.com/</a></li>
            <li><a href="https://woocommerce.com/">https://woocommerce.com/</a></li>
            <li><a href="https://www.volusion.com/">https://www.volusion.com/</a></li>
            <li><a href="http://www.wix.com/">http://www.wix.com/</a></li>
        </ul>
    </div>
</div>
</body>
</html>
